version: '3'

services:
  discordauth:
    image: muncs/discordauth
    restart: always
    networks:
      - web
    env_file:
      - .env
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.http.services.discord.loadbalancer.server.port=5000"
      - "traefik.http.routers.discord.rule=(Host(`discord.muncompsci.ca`))"
      - "traefik.http.routers.discord.entrypoints=websecure"
      - "traefik.http.routers.discord.tls.certresolver=myresolver"
networks:
  web:
    external: true
