version: '3'

services:
  discordauth:
    build: ./
    restart: always
    container_name: discordauth
    networks:
      - web
    expose:
      - 5000
    labels:
      traefik.enable: true
      traefik.frontend.rule: "Host: auth.muncompsci.ca"
      traefik.port: 5000
      traefik.frontend.entryPoints: "https"
    volumes:
      - ./:/app
networks:
  web:
    external: true
